### ISSUE TITLE
Implement functions for endpoint: Sources

### ISSUE THREAD

**Issue by sboysel** [sboysel/fredr#24]
https://research.stlouisfed.org/docs/api/fred/#Sources

The following endpoints need to be implemented properly and consistently in `fredr`:

- [x] `fredr_sources()` - Get all sources of economic data. (#34) 
- [x] `fredr_source()` - Get a source of economic data. (#34) 
- [x] `fredr_source_releases()` - Get the releases for a source. (#34) 

The functions are to be implemented with explicit arguments for each parameter in the FRED API (see [documentation](https://research.stlouisfed.org/docs/api/fred/#Series) for each endpoint and the discussion in #20).

**Comment by sboysel** [comment]
Closed with #34
